config/routes.rb
OpenDebate::Application.routes.draw do
  devise_for :users

  resources :debates do
    post :like
    collection do

      get :hot
      get :all

    end
  end

  resources :comments, only: [:create, :edit, :update]
  resources :likes, only: [:create, :destroy]
  root :to => 'debates#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :debate_id, :description, :user_id, :tag

  belongs_to :debate
  belongs_to :user

  validates :description, presence: true
end

app/models/debate.rb
class Debate < ActiveRecord::Base
  attr_accessible :description, :likes, :topic, :user_id

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  
  validates :topic, presence: true

  def self.trending_debates 
    debate_ids = Like.group(:debate_id).select('debate_id, COUNT(*) as debate_group').order('debate_group desc').limit(5).pluck(:debate_id)
    find_debates(debate_ids)
  end

  def self.hot_debates
    debate_ids = Comment.group(:debate_id).select('debate_id, COUNT(*) as debate_group').order('debate_group desc').limit(5).pluck(:debate_id)
    find_debates(debate_ids)
  end

  def self.count_comments (debate_id)
    Comment.find_all_by_debate_id(debate_id).count
  end

  def self.find_debates(debate_ids)
    debate_ids.uniq.map { |id| Debate.where(id: id).first}.compact
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :debate_id, :user_id
  belongs_to :user
  belongs_to :debate

  def self.like?(uid, did)
  	l = Like.find_by_user_id_and_debate_id(uid, did)
  	if not l
  		false
  	else
  		l
  	end
  end

  def self._count(did)
  	Like.find_all_by_debate_id(did).count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :user_name, :gender

  # attr_accessible :title, :body

  has_many :debates, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validate :email, format: {with: /^\w*[a-zA-Z]\w*@[a-z]+.[a-z]+/, message: 'Enter a valid email.'}
  validate :first_name, :last_name, format: {with: /^[a-zA-Z ]*/, message: 'Invalid name.'}
  validate :email, :user_name, uniqueness: true
  validates :first_name, :last_name, :user_name, :gender, :password, :password_confirmation, :email, presence: true

  def full_name
    first_name + ' ' + last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(params[:comment])
		# binding.pry
		if not(@comment.description == "")
			@comment.save!
			redirect_to debate_path(params[:comment][:debate_id])
		else
			# notice: "Cant perform blank comment."
			redirect_to :back
		end
		if @comment.save
  		flash[:notice] = 'comment posted!'
		else
  	  flash[:alert] = 'Comment cannot be left blank!'
		end		
	end

	def edit
	end
end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController
  # GET /debates
  # GET /debates.json

  def index
    
    @debates = Debate.trending_debates

    # @debates = Debate.find(trend)

    # binding.pry

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @debates }
    end
  end

  # GET /debates/1
  # GET /debates/1.json
  def show
    @debate = Debate.find(params[:id])

    @prev_like = Like.like?(current_user.id, params[:id])
    @like = Like.new

    # binding.pry
    
    @prev_comment = @debate.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @debate }
    end
  end

  # GET /debates/new
  # GET /debates/new.json
  def new
    @debate = Debate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @debate }
    end
  end

  # GET /debates/1/edit
  def edit
    @debate = Debate.find(params[:id])
  end

  # POST /debates
  # POST /debates.json
  def create

    @debate = Debate.new(params[:debate])
    @debate.user_id = current_user.id
    


    
    respond_to do |format|

      if @debate.save
        format.html { redirect_to @debate, notice: 'Debate was successfully created.' }
        format.json { render json: @debate, status: :created, location: @debate }
      else
        format.html { render action: "new" }
        format.json { render json: @debate.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /debates/1
  # PUT /debates/1.json

  def update
    @debate = Debate.find(params[:id])

    respond_to do |format|
      if @debate.update_attributes(params[:debate])
        format.html { redirect_to @debate, notice: 'Debate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @debate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debates/1
  # DELETE /debates/1.json
  def destroy
    @debate = Debate.find(params[:id])
    @debate.destroy

    respond_to do |format|
      format.html { redirect_to debates_url }
      format.json { head :no_content }
    end
  end

  def all
    @debates = Debate.all
  end

  def hot
    @debates = Debate.hot_debates

    # @debates = Debate.find(hot)
    # binding.pry
  end
  

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		
		
		@like = Like.new(debate_id: params[:debate_id], user_id: params[:user_id])
		
		@like.save!
		redirect_to :back
		
	end

	def destroy
		@like = Like.find(params[:id])
		@like.destroy


		redirect_to :back
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end
 
  # def bootstrap_class_for flash_type
  #   case flash_type
  #     when :success
  #       "alert-success"
  #     when :error
  #       "alert-error"
  #     when :alert
  #       "alert-block"
  #     when :notice
  #       "alert-info"
  #     else
  #       flash_type.to_s
  #   end
  # end
 
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/views/debates/_form.html.erb
<%= form_for(@debate) do |f| %>
  <% if @debate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debate.errors.count, "error") %> prohibited this debate from being saved:</h2>

      <ul>
      <% @debate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic %><br />
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.button :'Save changes', class: "btn btn-primary" %>
    <button type="button" class="btn">Cancel</button>
  </div>
<% end %>

app/views/debates/_list.html.erb
<div class="page-header">
  <%= button_to 'New Debate', new_debate_path, method: :get,  class: 'btn btn-primary' %> 
</div> 
<% @debates.each do |debate| %>
  
  <a href="<%= debate_path(debate) %>" class='debate' >
  <%# binding.pry%>
    <div>
      <h3><%= debate.topic %></h3>
      <p><%= debate.description %></p>
      <p><i>Uploaded by: </i><%= debate.user.first_name %></p>

      
      <div class='meta'>
        <%= time_ago_in_words(debate.created_at) +' ago' %>
        <% if (current_user && current_user.debate_ids.include?(debate.id)) %>
            | <%= link_to 'Edit', edit_debate_path(debate) %> |
            <%= link_to 'Delete', debate_path(debate), method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>
            <br>
        <% end %>
      </div> 
    </div>
  </a>
  <br/>

<% end %>

app/views/debates/all.html.erb
<h1>All Debates</h1>
<%= render 'list' %>

app/views/debates/edit.html.erb
<h1>Editing debate</h1>

<%= render 'form' %>

<%= link_to 'Show', @debate %> |
<%= link_to 'Back', debates_path %>

app/views/debates/hot.html.erb
 <h1>Hot Debates</h1>
<%= render 'list' %>

app/views/debates/index.html.erb
<h1>Trending Debates</h1>
<%= render 'list' %>

app/views/debates/new.html.erb
<h1>New debate</h1>

<%= render 'form' %>

<%= link_to 'Back', debates_path %>

app/views/debates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>
  	<%= @debate.topic %> | 
	  	<small>
	  		<%= @debate.user.email %>
	  	</small>
  </h2>
</p>
  

<h4><%= Like._count(@debate.id)%>
	<small>
		<% if not @prev_like %>
			<%= link_to "Trend it!", likes_path(debate_id: @debate.id, user_id: current_user.id), method: :post %>
		<%else%>
			<%= link_to "Untrend it!", like_path(@prev_like[:id]), method: :delete %>
		<%end%>
	</small>
</h4>

</br>

<p>
  <b>Description:</b><br />
  <%= @debate.description %>
</p>


<% @prev_comment.each do |comment| %>
	<p class="<%= comment.tag ? 'for' : 'against' %>">
		<strong><%= comment.user.user_name %> :</strong><br />
		<span><%= comment.description %></span>
	</p>
<%end%>

<%= form_for(@comment) do |f| %>
	-------------------------------------------------------
	<div class="field">
    	<%= f.text_area :description, placeholder: 'comment...' %>
	</div>

	<%= f.hidden_field :debate_id, value: @debate.id %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	
	<div class="field">
	    <%= f.radio_button :tag, "true", checked: true %>
	    <%= f.label :tag, "I'm with this.", :value => "true", class: "for" %><br>
	    <%= f.radio_button :tag, "false" %>
	    <%= f.label :tag, "I'm against this.", :value => "false", class: "against"  %>
  </div>

	<div class="actions">
		<%= f.button :Comment, class: "btn btn-primary" %>

	</div>
<%end%>



<%= link_to 'Back', debates_path %> 
 			<% if (current_user && current_user.debate_ids.include?(@debate.id)) %>
        
          | <%= link_to 'Edit', edit_debate_path(@debate) %> |
          <%= link_to 'Delete', debate_path(@debate), method: :delete, data: { confirm: 'Are you sure U want to delete?' } %>
       
      <% end %>


<style type="text/css">
	
.for {
	color: green;
}

.against {
	color: red;	
}

</style>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<head>
	  <title>OpenDebate</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>

	<body>	
		<br/><br/>
	  <% if notice || alert %>	
		  <div class="container">
		  	<br/>
		  	<% if notice %>
				  <p class="alert"><%= notice %></p>
				<% elsif alert %>
					<p class="alert"><%= alert %></p>
				<% end %>
			</div>	
		<% end %>

		<div class="container">
			<%= yield %>
		</div>
		
		<div class="navbar navbar-fixed-top">
			
			<div class="navbar-inner">
				<div class="container"> 
					<div class="container-fluid">
  						<div class="row-fluid">
    					
  						</div>
					</div>
					<a href="/debates" class="brand">OpenDebate</a>
					<div class="navbar-inner">
						<div class="container"> 
							<% if current_user %>
								<div style="float: right;">  Logged in as: <%= current_user.email%> 
				    			<%= link_to(' Logout', destroy_user_session_path, :method => :delete) %>
				  			</div>
			  			

								<ul class="nav">
									<li><%= link_to "All debates", all_debates_path %></li>
				          <li><%= link_to "Trending debates", debates_path %></li>
				          <li><%= link_to "Hot debates", hot_debates_path %></li>
								</ul>
								</div>
							<%end%>

					</div>
				</div>
			</div>
		</div>
	</body>
</html>